name       : roxterm
version    : 3.8.4
release    : 11
source     :
    - https://github.com/realh/roxterm/archive/3.8.4.tar.gz : 9424008c2db201c1a2664cb02c1932c28fae4a2ee5bec30b40e29c2079094933
license    : GPL-2.0-only
component  : system.utils
summary    : A tabbed, vte- (GTK+) based terminal emulator
description: |
    A tabbed, vte- (GTK+) based terminal emulator providing advanced features such as multiple tabs with a small footprint.
builddeps  :
    - pkgconfig(ImageMagick)
    - pkgconfig(dbus-1)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(python-2.7)
    - pkgconfig(vte-2.91)
    - docbook-xml
    - python-lockfile
    - itstool
    - po4a
    - xmlto
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
