name       : roxterm
version    : 3.3.2
release    : 3
source     :
    - http://heanet.dl.sourceforge.net/project/roxterm/roxterm/3.3.2/roxterm-3.3.2.tar.xz : 33501d698971fe80e2756104ffa5541aff23f0ae2b718464006d912ac93c506e
license    : GPL-2.0
summary    : A tabbed, vte- (GTK+) based terminal emulator
description: |
    A tabbed, vte- (GTK+) based terminal emulator providing advanced features such as multiple tabs with a small footprint.
builddeps  :
    - pkgconfig(dbus-1)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gmodule-2.0)
    - pkgconfig(ImageMagick)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(python-2.7)
    - pkgconfig(sm)
    - pkgconfig(vte-2.91)
    - pkgconfig(x11)
    - docbook-xml
    - python-lockfile
    - itstool
    - po4a
    - xmlto
setup      : |
    python mscript.py configure --prefix="/usr"
build      : |
    python mscript.py build
install    : |
    python mscript.py install --destdir="$installdir"
